# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversion.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import orbdetpy.rpc.messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='conversion.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\016org.astria.rpcB\021ConversionRequestP\000',
  serialized_pb=b'\n\x10\x63onversion.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0emessages.proto2\xcf\x02\n\nConversion\x12\x36\n\x0etransformFrame\x12\x14.TransformFrameInput\x1a\x0c.DoubleArray\"\x00\x12\x32\n\x12\x63onvertAzElToRaDec\x12\x0c.AnglesInput\x1a\x0c.DoubleArray\"\x00\x12\x32\n\x12\x63onvertRaDecToAzEl\x12\x0c.AnglesInput\x1a\x0c.DoubleArray\"\x00\x12L\n\x0cgetUTCString\x12\x1c.google.protobuf.DoubleValue\x1a\x1c.google.protobuf.StringValue\"\x00\x12S\n\x13getJ2000EpochOffset\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.DoubleValue\"\x00\x42%\n\x0eorg.astria.rpcB\x11\x43onversionRequestP\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_CONVERSION = _descriptor.ServiceDescriptor(
  name='Conversion',
  full_name='Conversion',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=404,
  methods=[
  _descriptor.MethodDescriptor(
    name='transformFrame',
    full_name='Conversion.transformFrame',
    index=0,
    containing_service=None,
    input_type=messages__pb2._TRANSFORMFRAMEINPUT,
    output_type=messages__pb2._DOUBLEARRAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='convertAzElToRaDec',
    full_name='Conversion.convertAzElToRaDec',
    index=1,
    containing_service=None,
    input_type=messages__pb2._ANGLESINPUT,
    output_type=messages__pb2._DOUBLEARRAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='convertRaDecToAzEl',
    full_name='Conversion.convertRaDecToAzEl',
    index=2,
    containing_service=None,
    input_type=messages__pb2._ANGLESINPUT,
    output_type=messages__pb2._DOUBLEARRAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getUTCString',
    full_name='Conversion.getUTCString',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getJ2000EpochOffset',
    full_name='Conversion.getJ2000EpochOffset',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERSION)

DESCRIPTOR.services_by_name['Conversion'] = _CONVERSION

# @@protoc_insertion_point(module_scope)
