# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estimation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import orbdetpy.rpc.messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='estimation.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\016org.astria.rpcB\021EstimationRequestP\000'),
  serialized_pb=_b('\n\x10\x65stimation.proto\x1a\x0emessages.proto2N\n\nEstimation\x12@\n\x0e\x64\x65termineOrbit\x12\x14.DetermineOrbitInput\x1a\x16.EstimationOutputArray\"\x00\x42%\n\x0eorg.astria.rpcB\x11\x45stimationRequestP\x00\x62\x06proto3')
  ,
  dependencies=[messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ESTIMATION = _descriptor.ServiceDescriptor(
  name='Estimation',
  full_name='Estimation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=36,
  serialized_end=114,
  methods=[
  _descriptor.MethodDescriptor(
    name='determineOrbit',
    full_name='Estimation.determineOrbit',
    index=0,
    containing_service=None,
    input_type=messages__pb2._DETERMINEORBITINPUT,
    output_type=messages__pb2._ESTIMATIONOUTPUTARRAY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTIMATION)

DESCRIPTOR.services_by_name['Estimation'] = _ESTIMATION

# @@protoc_insertion_point(module_scope)
