# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estimation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import orbdetpy.rpc.messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='estimation.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\016org.astria.rpcB\021EstimationRequestP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x65stimation.proto\x1a\x0emessages.proto2z\n\nEstimation\x12@\n\x0e\x64\x65termineOrbit\x12\x14.DetermineOrbitInput\x1a\x16.EstimationOutputArray\"\x00\x12*\n\niodLaplace\x12\x0c.AnglesInput\x1a\x0c.DoubleArray\"\x00\x42%\n\x0eorg.astria.rpcB\x11\x45stimationRequestP\x00\x62\x06proto3'
  ,
  dependencies=[messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ESTIMATION = _descriptor.ServiceDescriptor(
  name='Estimation',
  full_name='Estimation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=36,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='determineOrbit',
    full_name='Estimation.determineOrbit',
    index=0,
    containing_service=None,
    input_type=messages__pb2._DETERMINEORBITINPUT,
    output_type=messages__pb2._ESTIMATIONOUTPUTARRAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='iodLaplace',
    full_name='Estimation.iodLaplace',
    index=1,
    containing_service=None,
    input_type=messages__pb2._ANGLESINPUT,
    output_type=messages__pb2._DOUBLEARRAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTIMATION)

DESCRIPTOR.services_by_name['Estimation'] = _ESTIMATION

# @@protoc_insertion_point(module_scope)
