# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orbdetpy.rpc.messages_pb2 as messages__pb2


class EstimationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.determineOrbit = channel.unary_unary(
                '/Estimation/determineOrbit',
                request_serializer=messages__pb2.DetermineOrbitInput.SerializeToString,
                response_deserializer=messages__pb2.EstimationOutputArray.FromString,
                )
        self.iodLaplace = channel.unary_unary(
                '/Estimation/iodLaplace',
                request_serializer=messages__pb2.AnglesInput.SerializeToString,
                response_deserializer=messages__pb2.DoubleArray.FromString,
                )


class EstimationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def determineOrbit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def iodLaplace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstimationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'determineOrbit': grpc.unary_unary_rpc_method_handler(
                    servicer.determineOrbit,
                    request_deserializer=messages__pb2.DetermineOrbitInput.FromString,
                    response_serializer=messages__pb2.EstimationOutputArray.SerializeToString,
            ),
            'iodLaplace': grpc.unary_unary_rpc_method_handler(
                    servicer.iodLaplace,
                    request_deserializer=messages__pb2.AnglesInput.FromString,
                    response_serializer=messages__pb2.DoubleArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Estimation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Estimation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def determineOrbit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Estimation/determineOrbit',
            messages__pb2.DetermineOrbitInput.SerializeToString,
            messages__pb2.EstimationOutputArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def iodLaplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Estimation/iodLaplace',
            messages__pb2.AnglesInput.SerializeToString,
            messages__pb2.DoubleArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
