# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi_target.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import orbdetpy.rpc.messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='multi_target.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\016org.astria.rpcB\022MultiTargetRequestP\000',
  serialized_pb=b'\n\x12multi_target.proto\x1a\x0emessages.proto2H\n\x0bMultiTarget\x12\x39\n\x0e\x64\x65termineOrbit\x12\x11.MultiTargetInput\x1a\x12.MultiTargetOutput\"\x00\x42&\n\x0eorg.astria.rpcB\x12MultiTargetRequestP\x00\x62\x06proto3'
  ,
  dependencies=[messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_MULTITARGET = _descriptor.ServiceDescriptor(
  name='MultiTarget',
  full_name='MultiTarget',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=38,
  serialized_end=110,
  methods=[
  _descriptor.MethodDescriptor(
    name='determineOrbit',
    full_name='MultiTarget.determineOrbit',
    index=0,
    containing_service=None,
    input_type=messages__pb2._MULTITARGETINPUT,
    output_type=messages__pb2._MULTITARGETOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MULTITARGET)

DESCRIPTOR.services_by_name['MultiTarget'] = _MULTITARGET

# @@protoc_insertion_point(module_scope)
