# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: propagation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import orbdetpy.rpc.messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11propagation.proto\x1a\x0emessages.proto2A\n\x0bPropagation\x12\x32\n\tpropagate\x12\x0e.SettingsArray\x1a\x13.Measurement2DArray\"\x00\x42&\n\x0eorg.astria.rpcB\x12PropagationRequestP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'propagation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016org.astria.rpcB\022PropagationRequestP\000'
  _PROPAGATION._serialized_start=37
  _PROPAGATION._serialized_end=102
# @@protoc_insertion_point(module_scope)
