# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import orbdetpy.rpc.messages_pb2 as messages__pb2


class PropagationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.propagate = channel.unary_unary(
        '/Propagation/propagate',
        request_serializer=messages__pb2.SettingsArray.SerializeToString,
        response_deserializer=messages__pb2.PropagationOutputArray.FromString,
        )


class PropagationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def propagate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PropagationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'propagate': grpc.unary_unary_rpc_method_handler(
          servicer.propagate,
          request_deserializer=messages__pb2.SettingsArray.FromString,
          response_serializer=messages__pb2.PropagationOutputArray.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Propagation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
