# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import orbdetpy.protobuf.conversion_pb2 as conversion__pb2


class ConversionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.transformFrame = channel.unary_unary(
        '/Conversion/transformFrame',
        request_serializer=conversion__pb2.TransformFrameInput.SerializeToString,
        response_deserializer=conversion__pb2.TransformFrameOutput.FromString,
        )


class ConversionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def transformFrame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConversionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'transformFrame': grpc.unary_unary_rpc_method_handler(
          servicer.transformFrame,
          request_deserializer=conversion__pb2.TransformFrameInput.FromString,
          response_serializer=conversion__pb2.TransformFrameOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Conversion', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
