# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conversion.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\016org.astria.rpcB\021ConversionRequestP\000'),
  serialized_pb=_b('\n\x10\x63onversion.proto\"W\n\x13TransformFrameInput\x12\x11\n\tsrc_frame\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0b\n\x03pva\x18\x03 \x03(\x01\x12\x12\n\ndest_frame\x18\x04 \x01(\t\"#\n\x14TransformFrameOutput\x12\x0b\n\x03pva\x18\x01 \x03(\x01\x32M\n\nConversion\x12?\n\x0etransformFrame\x12\x14.TransformFrameInput\x1a\x15.TransformFrameOutput\"\x00\x42%\n\x0eorg.astria.rpcB\x11\x43onversionRequestP\x00\x62\x06proto3')
)




_TRANSFORMFRAMEINPUT = _descriptor.Descriptor(
  name='TransformFrameInput',
  full_name='TransformFrameInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_frame', full_name='TransformFrameInput.src_frame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='TransformFrameInput.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pva', full_name='TransformFrameInput.pva', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_frame', full_name='TransformFrameInput.dest_frame', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=107,
)


_TRANSFORMFRAMEOUTPUT = _descriptor.Descriptor(
  name='TransformFrameOutput',
  full_name='TransformFrameOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pva', full_name='TransformFrameOutput.pva', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['TransformFrameInput'] = _TRANSFORMFRAMEINPUT
DESCRIPTOR.message_types_by_name['TransformFrameOutput'] = _TRANSFORMFRAMEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransformFrameInput = _reflection.GeneratedProtocolMessageType('TransformFrameInput', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMFRAMEINPUT,
  '__module__' : 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:TransformFrameInput)
  })
_sym_db.RegisterMessage(TransformFrameInput)

TransformFrameOutput = _reflection.GeneratedProtocolMessageType('TransformFrameOutput', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMFRAMEOUTPUT,
  '__module__' : 'conversion_pb2'
  # @@protoc_insertion_point(class_scope:TransformFrameOutput)
  })
_sym_db.RegisterMessage(TransformFrameOutput)


DESCRIPTOR._options = None

_CONVERSION = _descriptor.ServiceDescriptor(
  name='Conversion',
  full_name='Conversion',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='transformFrame',
    full_name='Conversion.transformFrame',
    index=0,
    containing_service=None,
    input_type=_TRANSFORMFRAMEINPUT,
    output_type=_TRANSFORMFRAMEOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERSION)

DESCRIPTOR.services_by_name['Conversion'] = _CONVERSION

# @@protoc_insertion_point(module_scope)
