# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estimation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='estimation.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\016org.astria.rpcB\021EstimationRequestP\000'),
  serialized_pb=_b('\n\x10\x65stimation.proto\"E\n\x13\x44\x65termineOrbitInput\x12\x13\n\x0b\x63onfig_json\x18\x01 \x01(\t\x12\x19\n\x11measurements_json\x18\x02 \x01(\t\"/\n\x14\x44\x65termineOrbitOutput\x12\x17\n\x0f\x65stimation_json\x18\x01 \x01(\t2M\n\nEstimation\x12?\n\x0e\x64\x65termineOrbit\x12\x14.DetermineOrbitInput\x1a\x15.DetermineOrbitOutput\"\x00\x42%\n\x0eorg.astria.rpcB\x11\x45stimationRequestP\x00\x62\x06proto3')
)




_DETERMINEORBITINPUT = _descriptor.Descriptor(
  name='DetermineOrbitInput',
  full_name='DetermineOrbitInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_json', full_name='DetermineOrbitInput.config_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurements_json', full_name='DetermineOrbitInput.measurements_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=89,
)


_DETERMINEORBITOUTPUT = _descriptor.Descriptor(
  name='DetermineOrbitOutput',
  full_name='DetermineOrbitOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='estimation_json', full_name='DetermineOrbitOutput.estimation_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['DetermineOrbitInput'] = _DETERMINEORBITINPUT
DESCRIPTOR.message_types_by_name['DetermineOrbitOutput'] = _DETERMINEORBITOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetermineOrbitInput = _reflection.GeneratedProtocolMessageType('DetermineOrbitInput', (_message.Message,), {
  'DESCRIPTOR' : _DETERMINEORBITINPUT,
  '__module__' : 'estimation_pb2'
  # @@protoc_insertion_point(class_scope:DetermineOrbitInput)
  })
_sym_db.RegisterMessage(DetermineOrbitInput)

DetermineOrbitOutput = _reflection.GeneratedProtocolMessageType('DetermineOrbitOutput', (_message.Message,), {
  'DESCRIPTOR' : _DETERMINEORBITOUTPUT,
  '__module__' : 'estimation_pb2'
  # @@protoc_insertion_point(class_scope:DetermineOrbitOutput)
  })
_sym_db.RegisterMessage(DetermineOrbitOutput)


DESCRIPTOR._options = None

_ESTIMATION = _descriptor.ServiceDescriptor(
  name='Estimation',
  full_name='Estimation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=140,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='determineOrbit',
    full_name='Estimation.determineOrbit',
    index=0,
    containing_service=None,
    input_type=_DETERMINEORBITINPUT,
    output_type=_DETERMINEORBITOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTIMATION)

DESCRIPTOR.services_by_name['Estimation'] = _ESTIMATION

# @@protoc_insertion_point(module_scope)
