# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurements.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='measurements.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\016org.astria.rpcB\023MeasurementsRequestP\000'),
  serialized_pb=_b('\n\x12measurements.proto\"0\n\x19GenerateMeasurementsInput\x12\x13\n\x0b\x63onfig_json\x18\x01 \x01(\t\"7\n\x1aGenerateMeasurementsOutput\x12\x19\n\x11measurements_json\x18\x01 \x01(\t2a\n\x0cMeasurements\x12Q\n\x14generateMeasurements\x12\x1a.GenerateMeasurementsInput\x1a\x1b.GenerateMeasurementsOutput\"\x00\x42\'\n\x0eorg.astria.rpcB\x13MeasurementsRequestP\x00\x62\x06proto3')
)




_GENERATEMEASUREMENTSINPUT = _descriptor.Descriptor(
  name='GenerateMeasurementsInput',
  full_name='GenerateMeasurementsInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_json', full_name='GenerateMeasurementsInput.config_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=70,
)


_GENERATEMEASUREMENTSOUTPUT = _descriptor.Descriptor(
  name='GenerateMeasurementsOutput',
  full_name='GenerateMeasurementsOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurements_json', full_name='GenerateMeasurementsOutput.measurements_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['GenerateMeasurementsInput'] = _GENERATEMEASUREMENTSINPUT
DESCRIPTOR.message_types_by_name['GenerateMeasurementsOutput'] = _GENERATEMEASUREMENTSOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateMeasurementsInput = _reflection.GeneratedProtocolMessageType('GenerateMeasurementsInput', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEMEASUREMENTSINPUT,
  '__module__' : 'measurements_pb2'
  # @@protoc_insertion_point(class_scope:GenerateMeasurementsInput)
  })
_sym_db.RegisterMessage(GenerateMeasurementsInput)

GenerateMeasurementsOutput = _reflection.GeneratedProtocolMessageType('GenerateMeasurementsOutput', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEMEASUREMENTSOUTPUT,
  '__module__' : 'measurements_pb2'
  # @@protoc_insertion_point(class_scope:GenerateMeasurementsOutput)
  })
_sym_db.RegisterMessage(GenerateMeasurementsOutput)


DESCRIPTOR._options = None

_MEASUREMENTS = _descriptor.ServiceDescriptor(
  name='Measurements',
  full_name='Measurements',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=226,
  methods=[
  _descriptor.MethodDescriptor(
    name='generateMeasurements',
    full_name='Measurements.generateMeasurements',
    index=0,
    containing_service=None,
    input_type=_GENERATEMEASUREMENTSINPUT,
    output_type=_GENERATEMEASUREMENTSOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEASUREMENTS)

DESCRIPTOR.services_by_name['Measurements'] = _MEASUREMENTS

# @@protoc_insertion_point(module_scope)
