# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import orbdetpy.protobuf.measurements_pb2 as measurements__pb2


class MeasurementsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.generateMeasurements = channel.unary_unary(
        '/Measurements/generateMeasurements',
        request_serializer=measurements__pb2.GenerateMeasurementsInput.SerializeToString,
        response_deserializer=measurements__pb2.GenerateMeasurementsOutput.FromString,
        )


class MeasurementsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def generateMeasurements(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MeasurementsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'generateMeasurements': grpc.unary_unary_rpc_method_handler(
          servicer.generateMeasurements,
          request_deserializer=measurements__pb2.GenerateMeasurementsInput.FromString,
          response_serializer=measurements__pb2.GenerateMeasurementsOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Measurements', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
