# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import orbdetpy.protobuf.utilities_pb2 as utilities__pb2


class UtilitiesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.importTDM = channel.unary_unary(
        '/Utilities/importTDM',
        request_serializer=utilities__pb2.ImportTDMInput.SerializeToString,
        response_deserializer=utilities__pb2.ImportTDMOutput.FromString,
        )


class UtilitiesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def importTDM(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UtilitiesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'importTDM': grpc.unary_unary_rpc_method_handler(
          servicer.importTDM,
          request_deserializer=utilities__pb2.ImportTDMInput.FromString,
          response_serializer=utilities__pb2.ImportTDMOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Utilities', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
