# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utilities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='utilities.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\016org.astria.rpcB\020UtilitiesRequestP\000'),
  serialized_pb=_b('\n\x0futilities.proto\"8\n\x0eImportTDMInput\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0b\x66ile_format\x18\x02 \x01(\t\",\n\x0fImportTDMOutput\x12\x19\n\x11measurements_json\x18\x01 \x03(\t2=\n\tUtilities\x12\x30\n\timportTDM\x12\x0f.ImportTDMInput\x1a\x10.ImportTDMOutput\"\x00\x42$\n\x0eorg.astria.rpcB\x10UtilitiesRequestP\x00\x62\x06proto3')
)




_IMPORTTDMINPUT = _descriptor.Descriptor(
  name='ImportTDMInput',
  full_name='ImportTDMInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='ImportTDMInput.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_format', full_name='ImportTDMInput.file_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=75,
)


_IMPORTTDMOUTPUT = _descriptor.Descriptor(
  name='ImportTDMOutput',
  full_name='ImportTDMOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurements_json', full_name='ImportTDMOutput.measurements_json', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['ImportTDMInput'] = _IMPORTTDMINPUT
DESCRIPTOR.message_types_by_name['ImportTDMOutput'] = _IMPORTTDMOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImportTDMInput = _reflection.GeneratedProtocolMessageType('ImportTDMInput', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTTDMINPUT,
  '__module__' : 'utilities_pb2'
  # @@protoc_insertion_point(class_scope:ImportTDMInput)
  })
_sym_db.RegisterMessage(ImportTDMInput)

ImportTDMOutput = _reflection.GeneratedProtocolMessageType('ImportTDMOutput', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTTDMOUTPUT,
  '__module__' : 'utilities_pb2'
  # @@protoc_insertion_point(class_scope:ImportTDMOutput)
  })
_sym_db.RegisterMessage(ImportTDMOutput)


DESCRIPTOR._options = None

_UTILITIES = _descriptor.ServiceDescriptor(
  name='Utilities',
  full_name='Utilities',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='importTDM',
    full_name='Utilities.importTDM',
    index=0,
    containing_service=None,
    input_type=_IMPORTTDMINPUT,
    output_type=_IMPORTTDMOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UTILITIES)

DESCRIPTOR.services_by_name['Utilities'] = _UTILITIES

# @@protoc_insertion_point(module_scope)
